# Generated by Django 6.0.5 on 2026-07-12 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuente', models.CharField(choices=[('ninguna', 'Ninguna / Gasto'), ('salario', 'Salario'), ('servicios_profesionales', 'Servicios Profesionales'), ('freelance', 'Freelance'), ('dividendos', 'Dividendos'), ('intereses', 'Intereses'), ('ventas', 'Ventas'), ('obsequios', 'Obsequios'), ('otros', 'Otros')], default='ninguna', max_length=30)),
                ('categoria', models.CharField(choices=[('ninguna', 'Ninguna / Ingreso'), ('comida', 'Comida'), ('agua', 'Agua'), ('electricidad', 'Electricidad'), ('gas', 'Gas'), ('recreacion', 'Recreación'), ('entretenimiento', 'Entretenimiento'), ('pago_deudas', 'Pago de deudas'), ('otros', 'Otros')], default='ninguna', max_length=30)),
                ('fecha', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
